drops:
  - "STRING"
  - "GLOWSTONE_DUST"
  - "SUGAR"
  - "LEATHER"
  - "RABBIT_HIDE"
  - "RABBIT_FOOT"
  - "EGG"
  - "FEATHER"
  - "INK_SAC"
  - "CACTUS"
  - "CARROT"
  - "WHEAT_SEEDS"
  - "BEETROOT_SEEDS"
  - "MELON_SEEDS"
  - "PUMPKIN_SEEDS"
  - "POTATO"
  - "NETHER_WART"
  - "VINE"
  - "WHEAT"
  - "BEETROOT"
  - "MELON_SLICE"
  - "PUMPKIN"
  - "COCOA_BEANS"
  - "BAMBOO"
  - "BROWN_MUSHROOM"
  - "SUGAR_CANE"
  - "KELP"
  - "SWEET_BERRIES"
  - "SNOWBALL"
  - "CHORUS_FRUIT"
  - "CHORUS_FLOWER"
  - "OAK_SAPLING"
  - "SPRUCE_SAPLING"
  - "BIRCH_SAPLING"
  
  
item:
  material: HOPPER
  glow: true
  name: "&6| &fHopper de farm &6|"
  lore:
    - "&7&m------------------------"
    - "&8>> &fLe hopper permet de récupérer certains"
    - "&8>> &fles items dans un &cchunk&7."
    - "&7&m------------------------"